spring:
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        # Obligatoire pour envoyer vers la DLQ après les tentatives d'échec
        default-requeue-rejected: false 
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false